### ISSUE TITLE
mo_xor4096: Segfault with gfortran (8.3 and 10.2 tested) with -O3

### ISSUE THREAD

**Issue by MuellerSeb** [mcuntz/jams_fortran#1]
Hey there,
When executing the test program for `mo_xor4096` I get a segfault when compiling with gfortran and optimization level `-O3` (tested with version 8.3 and 10.2). With `-O2` the program runs and finishes successful.

I boiled it down to `-fpeel-loops` which is added with `-O3` (https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html).
When using `-O3 -fno-peel-loops`, the program also runs successful.

During compilation, I get these warnings, that are related to the problem (some more where the code is repeated again):
```bash
src/mo_xor4096.f90:2005:0:
           w(j) = w(j) + weyl
 
Warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
src/mo_xor4096.f90:2004:0:
         do k = 0, r - 1
 
note: within this loop
src/mo_xor4096.f90:1804:0:
         w = w + weyl
 
Warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
src/mo_xor4096.f90:1803:0:
       do k = 0, r - 1
 
note: within this loop
<...>
```

Maybe you have an idea what the deeper problem is. For now I am fine with using `-O3 -fno-peel-loops`.

Cheers,
Sebastian

**Comment by mcuntz** [comment]
Dear Sebastian,

random number generators often work with deliberate overflows, i.e. they keep on adding large numbers so that they pass the largest possible number for that kind and continue with a very negative value. This happens also in the xor4096 algorithm. The gfortran compiler does not seem to like that with -O3 (it had no problem in earlier versions). This is why I always had "-O3 -Wno-aggressive-loop-optimizations" as compiler flags if I used our library. I never figured out that it is "only" the loop expansion.

Now I recoded the initialisations of the number generators so that no deliberate overflow occurs.
Be aware that there are still other places where overflow can happen. But also gfortran does not seem to mind these.

Could you test that this resolves your problem, please. That would be great.

Kind regards,
Matthias

**Comment by mcuntz** [comment]
@MuellerSeb 
Hey Sebastian,

did you have a chance to test the mo_xor4096 module? It worked for me.

Kind regards,
Matthias

**Comment by MuellerSeb** [comment]
We will test this during next week. Will give you feedback than! Thanks for the help :-)

Cheers,
Sebastian

**Comment by MuellerSeb** [comment]
Everything works fine now. Thanks for this fix. Appreciated!

Cheers,
Sebastian

**Comment by mcuntz** [comment]
Great, I close the issue then.
Thanks for reporting @MuellerSeb and I will try to ping you  earlier next time ;-)
Matthias
